# Generated by Django 4.1.1 on 2022-10-22 16:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('hotness', models.FloatField(default=100)),
                ('ups', models.IntegerField(default=0)),
                ('downs', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('hotness', models.FloatField(default=100)),
                ('ups', models.IntegerField(default=0)),
                ('downs', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PriceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('term', models.CharField(choices=[('m', 'Monthly'), ('y', 'Yearly')], default='m', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='PriceGroupDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('hotness', models.FloatField(default=100)),
                ('ups', models.IntegerField(default=0)),
                ('downs', models.IntegerField(default=0)),
                ('group', models.ForeignKey(default='description', on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='core.pricegroup')),
            ],
        ),
        migrations.CreateModel(
            name='PriceAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('-', '-'), ('view', 'View'), ('hover', 'Hover'), ('select', 'Select'), ('unselect', 'Un-select'), ('signup_hover', 'Sing Up Hover'), ('signup_click', 'Sign Up Click'), ('purchase', 'Purchase')], default='-', max_length=100)),
                ('analytics_user_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('features', models.ManyToManyField(related_name='actions', to='core.groupfeature')),
                ('group_description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.pricegroupdescription')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.price')),
            ],
        ),
        migrations.AddField(
            model_name='price',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='core.pricegroup'),
        ),
        migrations.CreateModel(
            name='GroupFeatureSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.pricegroup')),
            ],
        ),
        migrations.AddField(
            model_name='groupfeature',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.groupfeatureslot'),
        ),
    ]
