# Generated by Django 4.1.2 on 2022-10-25 04:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analytics_user_id', models.UUIDField(default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='groupfeature',
            name='hotness',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='price',
            name='hotness',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pricegroupdescription',
            name='hotness',
            field=models.FloatField(default=0),
        ),
    ]
