# Generated by Django 4.1.2 on 2022-10-25 05:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_analyticsuser_alter_groupfeature_hotness_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyticsuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='analyticsuser',
            name='analytics_user_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
