# Generated by Django 4.1.2 on 2022-10-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_analyticsuser_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupfeature',
            name='users',
            field=models.ManyToManyField(related_name='features', to='core.analyticsuser'),
        ),
        migrations.AddField(
            model_name='price',
            name='users',
            field=models.ManyToManyField(related_name='prices', to='core.analyticsuser'),
        ),
        migrations.AddField(
            model_name='pricegroupdescription',
            name='users',
            field=models.ManyToManyField(related_name='descriptions', to='core.analyticsuser'),
        ),
    ]
