# Generated by Django 4.1.2 on 2022-10-25 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_analyticrecord_pricegroup_downs_pricegroup_hotness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticrecord',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_analytics', to='core.pricegroup'),
        ),
    ]
