# Generated by Django 4.1.2 on 2022-10-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_analyticrecord_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticrecord',
            name='action',
            field=models.CharField(choices=[('-', '-'), ('view', 'View'), ('hover', 'Hover'), ('leave', 'Leave'), ('select', 'Select'), ('unselect', 'Un-select'), ('signup_hover', 'Sing Up Hover'), ('signup_leave', 'Sing Up Leave'), ('signup_click', 'Sign Up Click'), ('purchase', 'Purchase')], default='-', max_length=100),
        ),
    ]
