# Generated by Django 4.1.2 on 2022-10-25 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_analyticrecord_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticrecord',
            name='group_description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='description_analytics', to='core.pricegroupdescription'),
        ),
        migrations.AlterField(
            model_name='analyticrecord',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_analytics', to='core.price'),
        ),
    ]
