# Generated by Django 4.1.2 on 2022-10-25 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_groupfeature_created_at_price_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticrecord',
            name='action',
            field=models.CharField(choices=[('-', '-'), ('view', 'View'), ('hover', 'Hover'), ('leave', 'Leave'), ('select', 'Select'), ('unselect', 'Un-select'), ('signup_hover', 'Sing Up Hover'), ('signup_leave', 'Sing Up Leave'), ('signup_click', 'Sign Up Click'), ('conversion_hover', 'Conversion Hover'), ('conversion_leave', 'Conversion Leave'), ('conversion_click', 'Conversion Click')], default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='groupfeature',
            name='slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.groupfeatureslot'),
        ),
    ]
