# Generated by Django 4.1.2 on 2022-10-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_pricegroup_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricegroup',
            name='term',
        ),
        migrations.AddField(
            model_name='price',
            name='term',
            field=models.CharField(choices=[('m', 'Monthly'), ('y', 'Yearly')], default='m', max_length=25),
        ),
    ]
