# Generated by Django 4.1.2 on 2022-10-30 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_alter_price_options_alter_price_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='term',
            field=models.CharField(blank=True, choices=[('', 'One-time'), ('mo', 'Monthly'), ('yr', 'Yearly')], default='mo', max_length=25, null=True),
        ),
        migrations.CreateModel(
            name='StripeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
