# Generated by Django 4.1.2 on 2022-10-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_price_term_stripeaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeaccount',
            name='business_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
