# Generated by Django 4.1.2 on 2022-10-30 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_stripeaccount_business_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricegroup',
            name='owner',
        ),
        migrations.AddField(
            model_name='pricegroup',
            name='stripe_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.stripeaccount'),
        ),
        migrations.AddField(
            model_name='stripeaccount',
            name='code',
            field=models.CharField(default=1234, max_length=255),
            preserve_default=False,
        ),
    ]
