# Generated by Django 4.1.2 on 2022-10-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_stripeaccount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricegroup',
            name='stripe_id',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
    ]
