# Generated by Django 4.1.2 on 2022-10-31 22:35

import app.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universal_id', models.CharField(default=app.utils.default_uuid_string, editable=False, max_length=255)),
                ('user_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universal_id', models.UUIDField(default=uuid.uuid5, editable=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('universal_id', models.UUIDField(default=uuid.uuid5, editable=False)),
                ('url', models.URLField()),
                ('stripe_account_id', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotness', models.FloatField(default=0)),
                ('ups', models.IntegerField(default=0)),
                ('downs', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('universal_id', models.UUIDField(default=uuid.uuid5, editable=False)),
                ('text', models.TextField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='app.component')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universal_id', models.UUIDField(default=uuid.uuid5, editable=False)),
                ('name', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_types', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='app.componenttype'),
        ),
        migrations.AddField(
            model_name='component',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='app.website'),
        ),
        migrations.CreateModel(
            name='Analytic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('-', '-'), ('view', 'View'), ('hover', 'Hover'), ('leave', 'Leave'), ('select', 'Select'), ('unselect', 'Un-select'), ('conversion', 'Conversion')], default='-', max_length=50)),
                ('analytic_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.analyticuser')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='app.content')),
            ],
        ),
    ]
