# Generated by Django 4.1.2 on 2022-11-01 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_token'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='token',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='website', to='core.token'),
        ),
        migrations.AlterField(
            model_name='website',
            name='stripe_account_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
