# Generated by Django 4.1.2 on 2022-11-01 02:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_website_token_alter_website_stripe_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='universal_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='componenttype',
            name='universal_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='content',
            name='universal_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='website',
            name='universal_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
