# Generated by Django 4.1.2 on 2022-11-01 07:42

import app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_analyticuser_website_alter_analytic_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytic',
            name='action',
            field=models.CharField(choices=[('-', '-'), ('click', 'Click'), ('focus', 'Focus'), ('blur', 'Blur'), ('mouseover', 'Hover'), ('mouseleave', 'Leave'), ('select', 'Select'), ('submit', 'Submit'), ('copy', 'Copy'), ('conversion', 'Conversion')], default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='analyticuser',
            name='universal_id',
            field=models.CharField(default=app.utils.default_uuid_string, max_length=255),
        ),
    ]
