# Generated by Django 4.1.2 on 2022-11-01 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_analytic_action_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analytic',
            old_name='action',
            new_name='event',
        ),
    ]
