# Generated by Django 4.1.2 on 2022-11-05 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_content_confidence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analytic',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['website__name', 'type__name', 'name']},
        ),
        migrations.AlterModelOptions(
            name='componenttype',
            options={'ordering': ['owner__email', 'name']},
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['component__name', '-hotness']},
        ),
        migrations.AlterModelOptions(
            name='contentcluster',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='website',
            options={'ordering': ['owner__email', 'name']},
        ),
        migrations.AddField(
            model_name='component',
            name='xpath',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='analytic',
            name='event',
            field=models.CharField(choices=[('-', '-'), ('click', 'Click'), ('focus', 'Select'), ('blur', 'Blur'), ('mouseover', 'Hover'), ('mouseleave', 'Leave'), ('select', 'Select'), ('submit', 'Submit'), ('copy', 'Copy'), ('view', 'View'), ('conversion', 'Conversion')], default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='content',
            name='confidence',
            field=models.FloatField(default=1),
        ),
    ]
