# Generated by Django 4.1.2 on 2022-11-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_token_created_at_token_expiry'),
        ('app', '0013_alter_analytic_options_alter_component_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='dynamic_add_tokens',
            field=models.ManyToManyField(related_name='dynamic_website_access', to='core.token'),
        ),
    ]
