# Generated by Django 4.1.2 on 2022-11-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_website_dynamic_add_tokens'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='component',
            constraint=models.UniqueConstraint(condition=models.Q(('xpath', ''), _negated=True), fields=('website', 'xpath'), name='unique_without_optional'),
        ),
    ]
