# Generated by Django 4.1.2 on 2022-11-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_component_unique_without_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='initial_content',
            field=models.TextField(default=''),
        ),
    ]
