# Generated by Django 4.1.2 on 2022-11-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_component_initial_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='element_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
