# Generated by Django 4.1.2 on 2022-11-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_component_element_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
    ]
