# Generated by Django 4.1.2 on 2022-11-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_componentconversionevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytic',
            name='event',
            field=models.CharField(choices=[('-', '-'), ('click', 'Click'), ('focus', 'Select'), ('blur', 'Blur'), ('mouseenter', 'Hover'), ('mouseleave', 'Leave'), ('select', 'Select'), ('submit', 'Submit'), ('copy', 'Copy'), ('view', 'View'), ('conversion', 'Conversion')], default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='componentconversionevent',
            name='event',
            field=models.CharField(choices=[('-', '-'), ('click', 'Click'), ('focus', 'Select'), ('blur', 'Blur'), ('mouseenter', 'Hover'), ('mouseleave', 'Leave'), ('select', 'Select'), ('submit', 'Submit'), ('copy', 'Copy'), ('view', 'View'), ('conversion', 'Conversion')], default='click', max_length=50),
        ),
    ]
