# Generated by Django 4.1.2 on 2022-11-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_component_css_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='css_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
