# Generated by Django 4.1.2 on 2022-11-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_component_css_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='element_type',
            field=models.CharField(choices=[('-', '-'), ('BUTTON', 'Button'), ('A', 'Link'), ('P', 'Paragraph'), ('H1', 'H1'), ('H2', 'H2'), ('H3', 'H3'), ('H4', 'H4'), ('H5', 'H5'), ('H6', 'H6'), ('DIV', 'Div'), ('SPAN', 'Span'), ('submit', 'Submit')], default='-', max_length=50),
        ),
    ]
