# Generated by Django 4.1.2 on 2022-11-05 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_component_element_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentconversionevent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_events', to='app.component'),
        ),
    ]
