# Generated by Django 4.1.2 on 2022-11-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_componentconversionevent_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytic',
            name='is_conversion',
            field=models.BooleanField(default=False),
        ),
    ]
