# Generated by Django 4.1.2 on 2022-11-05 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_component_element_class_component_element_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analytic',
            name='is_conversion',
        ),
        migrations.CreateModel(
            name='ConversionUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_paths', to='app.website')),
            ],
        ),
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='app.contentcluster')),
                ('conversion_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='app.conversionurl')),
            ],
        ),
    ]
