# Generated by Django 4.1.2 on 2022-11-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_analytic_is_conversion_conversionurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='go_live_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
