# Generated by Django 4.1.2 on 2022-11-07 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_componentconversionevent_value_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConversionUrl',
        ),
    ]
