# Generated by Django 4.1.2 on 2022-11-07 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_analytic_conversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytic',
            name='conversion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics', to='app.componentconversionevent'),
        ),
    ]
