# Generated by Django 4.1.2 on 2022-11-07 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_remove_analytic_conversion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversion',
            name='components',
        ),
    ]
