# Generated by Django 4.1.2 on 2022-11-09 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_remove_component_go_live_date_componentcampaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='current_campaign',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_component', to='app.componentcampaign'),
        ),
    ]
