# Generated by Django 4.1.2 on 2022-11-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_component_current_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='current_campaign',
        ),
        migrations.AddField(
            model_name='website',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
