# Generated by Django 4.1.2 on 2022-11-13 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_component_selector'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_suggestion',
            field=models.BooleanField(default=False),
        ),
    ]
